services:
  sidabi_db:
    container_name: sidabi_database
    restart: always
    build: 
      context: ./database_postgres
      dockerfile: Dockerfile
    # image: postgres:16
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database_postgres/pg_data:/var/lib/postgresql/data/
      # - ./database_postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database_postgres/pg_dump:/var/backups


  sidabi_app:
    container_name: sidabi_application
    build:
      context: ./sidabi_app
      dockerfile: Dockerfile
    ports:
      - 80:80
    expose:
      - 80
    volumes:
      - .:/var/www/html
    depends_on:
      sidabi_db:
        condition: service_started
    env_file:
      - .env
    networks:
      - sidabi_network

networks:
  sidabi_network:
    driver: bridge
